# Generated by Django 5.2.1 on 2025-06-28 17:37

from django.db import migrations

def ajouter_operateurs(apps, schema_editor):
    Operateur = apps.get_model('application', 'Operateur')
    Operateur.objects.bulk_create([
        Operateur(nom='MTN', type='mobile money', adresse='Abidjan Plateau'),
        Operateur(nom='Orange', type='mobile money', adresse='Cocody Angré'),
        Operateur(nom='Moov', type='telco', adresse='Yopougon Siporex'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(ajouter_operateurs),
    ]
