# Generated by Django 5.2.1 on 2025-06-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20250628_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_paiement',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
