# Generated by Django 5.2.1 on 2025-07-13 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_transaction_reference_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client_bancaire', 'Client bancaire'), ('client_operateur', 'Client opérateur'), ('agent', 'Agent'), ('admin', 'Administrateur')], default='client', max_length=16, verbose_name="Type d'utilisateur"),
        ),
    ]
