# Generated by Django 5.2.1 on 2025-07-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_operateur_utilisateur_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compte',
            name='compte_titulaire_ou_operateur',
        ),
        migrations.AddConstraint(
            model_name='compte',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('titulaire__isnull', False), ('type', 'banque')), models.Q(('titulaire__isnull', False), ('type', 'operateur')), models.Q(('operateur__isnull', False), ('type', 'operateur')), _connector='OR'), name='compte_titulaire_ou_operateur'),
        ),
    ]
