# Generated by Django 5.2.1 on 2025-07-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_compte_compte_titulaire_ou_operateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notification_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
